IMAGE_TYPE = ['image/jpeg','image/png','image/gif']
PDF_TYPE = ['application/pdf']
COMPRESS_TYPE = ['application/zip','application/x-rar']
DOCUMENT_TYPE = ['application/msword','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain']
COMMENTABLE_TYPE = ["Note", "Event", "Discussion"]
